steps:
- name: 'golang:1.11'
  entrypoint: 'make'
  args: ['test', 'dist']
  env: ['GO111MODULE=on', 'VERSION=v1.0.2']
artifacts:
  objects:
    location: 'gs://djmarkoz-docker-tail/'
    paths: ['bin/*']  